### ISSUE TITLE
Iterator interface

### ISSUE THREAD

**Issue by cgbur** [mccullocht/prefix_varint#14]
In previous leb128 crate I have made an iterator interface for the decoder. It accepts a `&[u8]` and returns an iterator of `Result<u64, Error>`. How would you feel about this being in this crate?

I think we could allow users to construct a `VarintIterator` from a `&[u8]` using a `from_bytes` method. Also could implement a `.iter_varint()` method on the `Bytes` trait to make it easier to construct.

**Comment by mccullocht** [comment]
I would be open to such a change.

I think the iterator should be templated on `PrefixVarInt` for consistency in the interface so it would yield `Result<PrefixVarInt, DecodeError>`.

Iterators over `Bytes` or `Read` are likely to have a very different implementation

**Comment by cgbur** [comment]
fixed by #15
