### ISSUE TITLE
Add extension methods to Read/Write

### ISSUE THREAD

**Issue by cgbur** [mccullocht/prefix_varint#18]
This would make it so if you had something that was `Write` you could do

```rust
writer_type.write_prefix_varint(val)
```

instead of needing to make the function call and put the arguments in the right order.

**Comment by mccullocht** [comment]
I had originally done it this way but then decided it may not be idiomatic since `Read` and `Write` interfaces only provide byte read. I haven't done any research so I'm not sure if it is common to extend these traits to read more complex types.
