### ISSUE TITLE
No api to calculate the encoded size ahead of time

### ISSUE THREAD

**Issue by cgbur** [mccullocht/prefix_varint#3]
In some cases it can be beneficial to calculate size ahead of time (allocation optimizations for compressors).

this math transferred from leb128 seems to work but may be a better way.

```rust
pub fn get_leb128_encoding_length(x: u64) -> usize {
    // use max to handle case of 0
    std::cmp::max(1, ((7 + 64 - x.leading_zeros() - 1) / 7) as usize)
}
```

**Comment by mccullocht** [comment]
Something similar should work but there's an edge case when the highest bit is set: leb will produce a 10 byte encoding but prefix will only produce 9 (0xff + 8 byte big endian encoding) -- effectively max at 9.
